name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          # Use the GitHub run number as a simple incrementing tag
          IMAGE_TAG=sakibmondal7/users_module:V${{ github.run_number }}
          docker build . --file Dockerfile --tag $IMAGE_TAG

      - name: Push Docker image
        run: |
          IMAGE_TAG=sakibmondal7/users_module:${{ github.run_number }}
          docker push $IMAGE_TAG

      - name: Tag image as latest and push
        run: |
          IMAGE_TAG=sakibmondal7/users_module:${{ github.run_number }}
          docker tag $IMAGE_TAG sakibmondal7/users_module:latest
          docker push sakibmondal7/users_module:latest