name: Docker Image Build test

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'BACKEND/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'BACKEND/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image (test only)
        run: |
          docker build BACKEND/ --file BACKEND/Dockerfile --tag test-image:build-check