name: Deploy on Main Push

on:
  push:
    branches: [ "main" ]  

jobs:
  trigger-deployment:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Deployment Webhook
      env:
        DEPLOY_HOOK_URL: ${{ secrets.DEPLOY_HOOK_URL }}
      run: |
        echo "Triggering deployment..."
        curl -X POST "$DEPLOY_HOOK_URL"